name: ecom_data_gen_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pandas
  - pyyaml
  - faker
  - jupyter
  - sqlite
  - numpy
  - ipykernel
  - pip:
      - black
      - ruff
      - pytest
      - matplotlib
      - plotly
