# ------------------------------------------------------------------------------
# 📦 ecom_sales_gen_template.yaml
# ------------------------------------------------------------------------------
# This YAML configuration file controls the full synthetic data generation
# pipeline for the e-commerce sales and returns simulator.
#
# It defines:
# - Generator paths to module functions
# - Table schemas and generation logic
# - Controlled vocabularies for realism
# - Messiness injection parameters
# - Channel-specific behavioral rules
#
# 👉 Use this as a teaching template and starting point to build your own
# data generation stories. This template is aligned with `run_data_generation.py`
# and expects a compatible folder structure under `src/`.
#
# For usage:
#   ecomgen --config config/ecom_sales_gen_template.yaml --messiness-level light_mess
# ------------------------------------------------------------------------------

# -------------------- DATA GENERATION FUNCTIONS --------------------
# These are the import paths to Python generator functions. Each maps
# to a table name and should return a list of dictionaries or rows.
row_generators:
  shopping_carts: generators.generator_carts.generate_shopping_carts
  cart_items: generators.generator_carts.generate_cart_items
  orders: generators.generator_orders.generate_orders
  order_items: generators.generator_orders.generate_order_items
  returns: generators.generator_returns.generate_returns
  return_items: generators.generator_returns.generate_return_items
  customers: generators.generator_customers.customer_lookup_generator
  product_catalog: generators.generator_catalog.product_catalog_lookup_generator

output_dir: output

faker_seed: 42

 # -------------------- TABLE SCHEMAS --------------------
 # This section defines each table in the generated dataset.
 #
 # Structure:
 # - `name`: the table's name (used for CSV and SQL export)
 # - `generate`: how many rows to create (if applicable)
 # - `columns`: the schema definition (column name and data type)
 #
 # Special Fields:
 # - `link_to_orders: true`: used for child tables (e.g., order_items, return_items)
 #   that depend on existing orders.
 # - `item_count_range`: specifies how many items to generate per parent row.
 #
 # Common Column Types:
 # - `TEXT`, `INTEGER`, `REAL`, `BOOLEAN`, `DATE`
 # - Some columns accept `options`, `probabilities`, or conditional rules.
 #
 # Purpose:
 # Use this section to control the structure and relationships of your data.
 # You can define parent-child links (orders → order_items), add conditional logic
 # for data integrity, and simulate realistic retail scenarios.
tables:
  - name: customers
    columns:
      - { name: customer_id, type: TEXT }
      - { name: first_name, type: TEXT }
      - { name: last_name, type: TEXT }
      - { name: email, type: TEXT }
      - { name: phone_number, type: TEXT }
      - { name: address, type: TEXT }
      - { name: city, type: TEXT }
      - { name: state, type: TEXT }
      - { name: zip_code, type: TEXT }
      - { name: country, type: TEXT }
      - { name: signup_date, type: DATE }
      - { name: gender, type: TEXT }
      - { name: age, type: INTEGER }
      - { name: is_guest, type: BOOLEAN }
      - { name: customer_status, type: TEXT, options: ["Active", "Inactive"], probabilities: [0.9, 0.1] }
      - { name: signup_channel, type: TEXT }
      - { name: loyalty_tier, type: TEXT, options: ["Bronze", "Silver", "Gold", "Platinum"] }
      - { name: email_verified, type: BOOLEAN }
      - { name: marketing_opt_in, type: BOOLEAN }
      - { name: mailing_address, type: TEXT }
      - { name: billing_address, type: TEXT }
      - { name: loyalty_enrollment_date, type: DATE }
      - { name: clv_bucket, type: TEXT }

  - name: product_catalog
    columns:
      - { name: product_id, type: INTEGER }
      - { name: product_name, type: TEXT }
      - { name: category, type: TEXT }
      - { name: unit_price, type: REAL }
      - { name: inventory_quantity, type: INTEGER }

  - name: shopping_carts
    generate: 50000 # Increase traffic for a mid-sized retailer scenario.
    columns:
      - { name: cart_id, type: TEXT }
      - { name: customer_id, type: TEXT }
      - { name: created_at, type: DATE }
      - { name: cart_total, type: REAL }
      - { name: status, type: TEXT } # open, converted, abandoned

  - name: cart_items
    link_to_carts: true
    item_count_range: [1, 8]
    columns:
      - { name: cart_item_id, type: INTEGER }
      - { name: cart_id, type: TEXT }
      - { name: product_id, type: INTEGER }
      - { name: product_name, type: TEXT }
      - { name: category, type: TEXT }
      - { name: quantity, type: INTEGER }
      - { name: unit_price, type: REAL }

  - name: orders
    # The 'generate' key is now ignored for orders. The number of orders is
    # determined by the number of converted shopping carts.
    columns:
      - name: order_id
        type: TEXT
      - name: total_items
        type: INTEGER
      - name: order_date
        type: DATE
      - name: customer_id
        type: TEXT
      - name: email
        type: TEXT
      - name: order_channel
        type: TEXT
      - name: is_expedited
        type: BOOLEAN
      - name: customer_tier
        type: TEXT
      - name: order_total
        type: REAL
      - name: payment_method
        type: TEXT
      - name: shipping_speed
        type: TEXT
      - name: shipping_cost
        type: REAL
      - name: agent_id
        type: TEXT
      - name: shipping_address
        type: TEXT
      - name: billing_address
        type: TEXT
      - name: clv_bucket
        type: TEXT

  - name: order_items # Derived from cart_items of converted carts
    link_to_orders: true    # Dynamically generates N items per existing order
    item_count_range: [1, 10]     # NEW: Alnones between 1 and 10 items per order
    columns:
      - name: order_id
        type: TEXT
      - name: product_id
        type: INTEGER
      - name: product_name
        type: TEXT
      - name: category
        type: TEXT
      - name: quantity
        type: INTEGER
      - name: unit_price
        type: REAL

  - name: returns
    # The 'generate' key is now ignored. The number of returns is determined
    # by the number of orders and the configured return_rate.
    columns:
      - name: return_id
        type: TEXT
      - name: order_id
        type: TEXT
      - name: customer_id
        type: TEXT
      - name: email
        type: TEXT
      - name: return_date
        type: DATE
      - name: reason
        type: TEXT
      - name: return_type
        type: TEXT
      - name: refunded_amount
        type: REAL
      - name: return_channel
        type: TEXT
      - name: agent_id
        type: TEXT
      - name: refund_method 
        type: TEXT

  - name: return_items
    columns:
      - name: return_item_id
        type: INTEGER
      - name: return_id
        type: TEXT
      - name: order_id
        type: TEXT
      - name: product_id
        type: INTEGER
      - name: product_name
        type: TEXT
      - name: category
        type: TEXT 
      - name: quantity_returned
        type: INTEGER
      - name: unit_price
        type: REAL
      - name: refunded_amount
        type: REAL

# -------------------- LOOKUP TABLE CONFIG --------------------
# Optional generators for controlled vocab tables like customers or products.
# These are cached and reused across dependent tables.
lookup_config:
  product_catalog:
    num_products: 1286
    min_price: 5.0
    max_price: 250.0
    min_inventory_quantity: 50
    max_inventory_quantity: 100
    generator: generators.generator_catalog.generate_product_catalog
  customers:
    num_customers: 50000 # Increase the total customer base.
    min_age: 18
    max_age: 70
    gender_unknown_prob: 0.05
    guest_shopper_pct: 0.4
    generator: generators.generator_customers.generate_customers


# -------------------- VOCABULARY AND PARAMETERS SECTION --------------------
# These control value distributions for categorical fields and realism factors.
vocab:
  category_vocab:
    electronics:
      adjectives:
        - Wireless
        - Compact
        - Smart
        - Portable
      nouns:
        - Speaker
        - Headphones
        - Camera
        - Monitor
    clothing:
      adjectives:
        - Comfortable
        - Stylish
        - Classic
        - Durable
      nouns:
        - Jacket
        - Jeans
        - Sweater
        - Shirt
    books:
      adjectives:
        - Illustrated
        - Hardcover
        - Classic
        - Modern
      nouns:
        - Novel
        - Guide
        - Anthology
        - Memoir
    home:
      adjectives:
        - Elegant
        - Rustic
        - Cozy
        - Modern
      nouns:
        - Lamp
        - Rug
        - Chair
        - Table
    toys:
      adjectives:
        - Fun
        - Educational
        - Colorful
        - Interactive
      nouns:
        - Puzzle
        - Doll
        - Blocks
        - Car
  regions:
    - North
    - South
    - East
    - West
    - Central

  payment_methods:
    - Credit Card
    - PayPal
    - Apple Pay
    - Google Pay
    - ACH
    - Ebay
    - NewEgg

  customer_tiers:
    - Bronze
    - Silver
    - Gold
    - Platinum

  shipping_speeds:
    - Standard
    - Two-Day
    - Overnight

  return_reasons:
    - Defective
    - Wrong item
    - Arrived damaged
    - Product did not match description
    - Found a better price
    - Item arrived late
    - No longer needed
    - Damaged in transit
    - Changed mind

  order_channels:
    - Web
    - Phone
    - Social Media
    - Ebay
    - NewEgg


  return_channels:
    - Web
    - Phone
    - Social Media
    - Ebay
    - NewEgg

  categories:
    - Electronics
    - Clothing
    - Books
    - Home
    - Toys

  genders:
    - Male
    - Female
    - Unknown

  signup_channels:
    - Website
    - Phone
    - email
    - Social Media

  loyalty_tiers:
    - Bronze
    - Silver
    - Gold
    - Platinum

  clv_buckets:
    - Low
    - Medium
    - High

  agent_pool:
    enabled: true
    agents:
      - id: CSR-0001
        name: Alice Johnson
      - id: CSR-0002
        name: Bob Smith
      - id: CSR-0003
        name: Carol Davis
      - id: CSR-0004
        name: David Lee
      - id: CSR-0005
        name: Eva Martinez
      - id: CSR-0006
        name: Frank Wilson
      - id: CSR-0007
        name: Grace Kim
      - id: CSR-0008
        name: Henry Clark
      - id: CSR-0009
        name: Irene Lopez
      - id: CSR-0010
        name: Jack Turner
      - id: CSR-0011
        name: Karen Evans
      - id: CSR-0012
        name: Larry Scott
      - id: CSR-0013
        name: Monica White
      - id: CSR-0014
        name: Nathan Young
      - id: CSR-0015
        name: Olivia King
      - id: CSR-0016
        name: Paul Green
      - id: CSR-0017
        name: Queenie Harris
      - id: CSR-0018
        name: Robert Adams
      - id: CSR-0019
        name: Susan Baker
      - id: CSR-0020
        name: Tom Nelson

# -------------------- GLOBAL PARAMETERS --------------------
# These affect core generator logic: signup timelines, distributions,
# shipping rules, return biases, etc.
parameters:
  signup_years: 1 # Controls the historical depth of customer signups. Aligns with 1-year of order history.
  expedited_pct: 20
  gender_unknown_prob: 5
  order_days_back: 365
  conversion_rate: 0.068 # Set to 6.8% for a slightly below-average conversion.
  return_max_lag_days: 30
  # NEW: Settings to control repeat purchase behavior for cohort analysis
  repeat_purchase_settings:
    # NOTE: These values represent the AVERAGE NUMBER of repeat visits (lambda for a Poisson distribution).
    # They are calculated to produce realistic repeat PURCHASE rates after accounting for the conversion_rate.
    # A loyal customer may visit many times before their next purchase.
    propensity_by_tier:
      Platinum: 7.5  # Targets ~40% repeat purchase rate
      Gold: 5.2      # Targets ~30% repeat purchase rate
      Silver: 3.3    # Targets ~20% repeat purchase rate
      Bronze: 1.5    # Targets ~10% repeat purchase rate
      default: 0.75  # For guests and no-tier, targets ~5% repeat purchase rate
    # Time delay in days between a purchase and the next visit
    time_delay_days_range: [20, 90]
  return_rate: 0.25 # NEW: Generate returns for 25% of all orders.
  # Distribution of orders by channel reflecting typical online retailer data
  order_channel_distribution: #
    Web: 0.60
    Phone: 0.15
    Social Media: 0.10 # NEW
    Ebay: 0.10         # NEW
    NewEgg: 0.05       # NEW
  shipping_speed_distribution:
    Standard: 0.65
    Two-Day: 0.20
    Overnight: 0.15
  shipping_costs:
    Standard: 5.0
    Two-Day: 45.0
    Overnight: 80.0
  free_shipping_pct: 0
  free_shipping_min_order: 100.0
  return_channel_preference_prob: 0.90 # NEW: 90% chance returns follow their order channel preference. Adjust as needed.
  global_payment_method_distribution: # NEW: Default payment method distribution for channels without specific rules
    Credit Card: 0.60
    PayPal: 0.20
    Apple Pay: 0.10
    Google Pay: 0.05
    ACH: 0.05
    Cash: 0.00 # Add if you plan to simulate cash payments for In-Store or other channels
    Ebay: 0.00 # Set to 0 if only used for specific channel rules
    NewEgg: 0.00 # Set to 0 if only used for specific channel rules

  # --- Advanced Messiness Injection Parameters ---
  seasonal_spike_factors:
    medium:
      11: 1.4  # November
      12: 1.6  # December
    high:
      11: 1.8  # November
      12: 2.2  # December
      7: 1.3   # July

  # --- Contextual Return Rate Parameters ---
  category_return_rates:
    electronics: 0.35  # Higher rate for complex items or compatibility issues
    clothing: 0.30     # Sizing issues are common
    books: 0.05        # Very low return rate
    home: 0.15
    toys: 0.10
    default: 0.20      # A fallback default rate for categories not specified

# --- Baseline Return Reason Distribution ---
# Each category defines the likelihood of return reasons.
# Values are percentages and must sum to 100% per category.
  baseline_return_reason_weights:
    electronics:
      "Defective": 0.4
      "Product did not match description": 0.2
      "Arrived damaged": 0.1
      "Changed mind": 0.1
      "No longer needed": 0.2
    clothing:
      "Changed mind": 0.5
      "Wrong item": 0.3 # Sizing issues fall here
      "Defective": 0.1
      "Product did not match description": 0.1
    books:
      "Wrong item": 0.4
      "Changed mind": 0.3
      "Arrived damaged": 0.3 # e.g., bent cover
    default: # Fallback for home, toys, etc.
      "No longer needed": 0.2
      "Changed mind": 0.1
      "Found a better price": 0.3
      "Product did not match description": 0.2
      "Defective": 0.1
      "Arrived damaged": 0.1

  return_reason_bias_schemas:
    medium:
      electronics:
        "Defective": 0.5
        "Product did not match description": 0.3
        "Arrived damaged": 0.2
      clothing:
        "Changed mind": 0.4
        "Wrong item": 0.2
        "Defective": 0.2
        "Item arrived late": 0.2
      default: # Fallback for other categories
        "No longer needed": 0.1
        "Defective": 0.2
        "Found a better price": 0.2
        "Changed mind": 0.1
        "Product did not match description": 0.1
        "Item arrived late": 0.3
    high:
      electronics:
        "Defective": 0.6
        "Arrived damaged": 0.3
        "Damaged in transit": 0.1
      clothing:
        "Wrong item": 0.5
        "Changed mind": 0.3
        "Arrived damaged": 0.2
      default:
        "Arrived damaged": 0.5
        "Item arrived late": 0.3
        "No longer needed": 0.2

# -------------------- CHANNEL-SPECIFIC RULES --------------------
# Overrides by order_channel. You can define allowed payment methods
# and preferred return channels per channel (e.g., eBay, Web).
channel_rules: #
  # Rules for each order_channel
  Web:
    allowed_payment_methods: ["Credit Card", "ACH", "PayPal", "Apple Pay", "Google Pay"]
    return_channel_preference: "Web" # Orders from Web prefer returns via Web
  Phone:
    allowed_payment_methods: ["Credit Card", "ACH"] # Phone is constrained
    return_channel_preference: "Phone" # Orders from Phone prefer returns via Phone
  Social Media:
    # Use global_payment_method_distribution
    allowed_payment_methods: ["Credit Card", "PayPal", "Apple Pay", "Google Pay"]
    return_channel_preference: "Social Media"
  Ebay:
    allowed_payment_methods: ["Ebay"] # eBay is tightly coupled with PayPal.
    return_channel_preference: "Ebay" # Returns typically via eBay.
  NewEgg:
    allowed_payment_methods: ["NewEgg"] # Assuming NewEgg has its own payment type
    return_channel_preference: "NewEgg" # Returns typically via NewEgg platform
